version: '3.8'
services: 
  sweb:
    container_name: johanSweb
    build: 
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=johan
      - PASSWD=johan
      - HOSTNAME=johanSweb.asir.es
    networks: 
      asir.es:
          ipv4_address: 176.120.10.2


  SBD:
      container_name: johanGBD
    build: 
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=johan
      - PASSWD=johan
      - HOSTNAME=johanSBD.asir.es
    networks: 
      asir.es:
          ipv4_address: 176.120.10.3