version: '3.8'
services: 
  Sweb: #lo pones el mayúscula
    container_name: carlosSweb 
    build: 
      context: ./carlosSweb
      dockerfile: ./carlosSweb/dockerfile #./Dockerfile --> el directorio y lo indicas en 'context'
    environment: 
      - USUARIO=carlos
      - PSSWD=1234 #No coincide con la variable ${PASSWD} es start.sh
      - HOSTNAME=carlosSweb.asir.es
    networks:
      netasir:
          ipv4_address: 174.120.10.2
  Sweb: #repites el mismo servicio
    container_name: carlosSBD 
    build: 
      context: ./carlosSBD
      dockerfile: ./carlosSBD/dockerfile #./Dockerfile --> el directorio y lo indicas en 'context'
    environment: 
      - USUARIO=carlos
      - PSSWD=1234
      - HOSTNAME=carlosSweb.asir.es
    networks:
      netasir:
          ipv4_address: 174.120.10.3
networks: 
  netasir:
      ipam: 
          driver: default
          config: 
              - subnet: 174.120.10.0/24
