version: '3.8'
services:
  Sweb:
    container_name: servWeb
    build: 
      context: ./morgadoSweb
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=morgado
      - PASSWD=usuario
      - HOSTNAME=morgadoSweb.asir.es
    ports: 
      - "80:80"
    networks: 
      netasir:
          ipv4_address: 172.124.10.2 
  SBD:
    container_name: servBD
    build: 
      context: ./morgadoSBD
      dockerfile: ./Dockerfile
    environment: 
      - USUARIO=morgado
      - PASSWD=usuario
      - HOSTNAME=morgadoSBD.asir.es
    networks: 
      netasir:
          ipv4_address: 172.124.10.3 
networks: 
  netasir:
      ipam: 
          driver: default
          config: 
              - subnet: 172.124.10.0/24

