version: '3.8'
services:
  sweb:
    container_name: jcarlosSweb
    build:
      context: ./jcarlosSweb
      dockerfile: ./Dockerfile
    environment:
      - USUARIO=jcarlos
      - PASSWD=1234
      - Hostname=jcarlosSweb.asir.es
    networks:
      netasir:
        ipv4_address: 173.120.10.2
  sbd:
    container_name: jcarlosSBD
    build:
      context: ./jcarlosSBD
      dockerfile: ./Dockerfile
    environment:
      - USUARIO=jcarlos
      - PASSWD=1234
      - Hostname=jcarlosSBD.asir.es
    networks:
      netasir:
          ipv4_address: 173.120.10.3
networks:
  netasir:
      ipam:
          driver: default
          config:
              - subnet: 173.120.10.0/24